Repository wecode-bootcamp-korea/38-1st-WESH-Korea-backend, pull requests merged in 2022-10, with the labels that each got.

#4 migration 수정
  db/migrations/20221019085921_likes_add_unique.sql
  db/migrations/20221019085939_products_add_column.sql
Labels: 멘토 리뷰 요청

#2 [ADD] 유저 회원가입 및 로그인
  api/controllers/userController.js
  api/models/appDataSource.js
  api/models/userDao.js
  api/routes/index.js
  api/routes/userRouter.js
  api/services/userService.js
  api/utils/auth.js
  api/utils/error.js
  app.js
Labels: 완료

#7 [ADD] 유저 회원가입 및 로그인
  api/controllers/userController.js
  api/models/userDao.js
  api/utils/auth.js
Labels: 멘토 리뷰 요청

#9 Cart CRUD 구현
  api/controllers/cartController.js
  api/models/cartDao.js
  api/routes/cartRoute.js
  api/routes/index.js
  api/services/cartService.js
  api/utils/auth.js
Labels: 멘토 리뷰 요청

#11 user point 조회, point 수정 기능 구현
  api/models/userDao.js
Labels: 멘토 리뷰 요청

#16 [ADD] 제품 상세페이지 구현
  api/controllers/productController.js
  api/models/productDao.js
  api/routes/index.js
  api/routes/productRouter.js
  api/services/productService.js
Labels: 멘토 리뷰 요청

#14 유저 마이페이지 기능 구현 : 해당 유저에 맞는 개인 정보 및 상품 주문 현황 정보 response
  api/controllers/userController.js
  api/models/userDao.js
  api/routes/userRouter.js
  api/services/userService.js
Labels: 멘토 리뷰 요청

#18 [ADD] 이벤트 상품 페이지 리뷰CRUD 구현
  api/controllers/eventCommentController.js
  api/models/eventCommentDao.js
  api/routes/eventCommentRouter.js
  api/routes/index.js
  api/services/eventCommentService.js
Labels: 멘토 리뷰 요청

#22 Hotfix
  api/routes/index.js
Labels: 멘토 리뷰 요청

#19 Like function
  api/controllers/likeController.js
  api/models/likeDao.js
  api/routes/index.js
  api/routes/likeRouter.js
  api/routes/userRouter.js
  api/services/likeService.js
Labels: 멘토 리뷰 요청

#13 Get product info
  api/controllers/productController.js
  api/controllers/reviewController.js
  api/controllers/userController.js
  api/models/productDao.js
  api/routes/index.js
  api/routes/productRouter.js
  api/routes/reviewRouter.js
  api/routes/userRouter.js
  api/services/productService.js
  api/services/userService.js
  api/utils/auth.js
Labels: Conflict 해결 요청, 수정 요청

#20 [ADD] 태그별 제품 가격순 필터링
  api/controllers/productFilterController.js
  api/models/productFilterDao.js
  api/routes/index.js
  api/routes/productFilterRouter.js
  api/services/productFilterService.js
Labels: 완료

#10 order add 구현
  api/controllers/orderController.js
  api/models/enums.js
  api/models/orderDao.js
  api/routes/index.js
  api/routes/orderRouter.js
  api/services/orderService.js
Labels: 멘토 리뷰 요청
